### ISSUE TITLE
pdfcutter feature

### ISSUE THREAD

**Issue by akvhumbu** [stefanw/pdfcutter#1]
Hi Stefan,

I stumbled upon your python script while looking for a script that can split an 11 * 17 inch paper size document into 2 11 *8.5 inch paper size files. The idea is to link a pdf file and have a new copy saved that is split. Do you have such a script or could you point me to one?

Regards,
 Tony

**Comment by stefanw** [comment]
`pdfcutter` is not what you want, as it is about extracting ('cutting') specific pieces of text out of a PDF.

It sounds like what you want is to print a PDF page to a different paper size, maybe a print to pdf process might help you. If you're looking for poster generation, try [PosteRazor](https://posterazor.sourceforge.io/).
